apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: azure-static-web-scorm
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - {{ .Values.istio.scormHost }}
  ports:
    - number: 443
      name: https
      protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
