{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.networkPolicy.operatorEgressName }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: keycloak-operator
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        {{- range .Values.networkPolicy.external.ports }}
        - protocol: TCP
          port: {{ . }}
        {{- end }}

    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.dns.namespace }}
          podSelector:
            matchLabels:
              {{- range $key, $value := .Values.networkPolicy.dns.podSelector }}
              {{ $key }}: {{ $value | quote }}
              {{- end }}
      ports:
        - protocol: {{ .Values.networkPolicy.dns.protocol }}
          port: {{ .Values.networkPolicy.dns.port }}
        - protocol: TCP
          port: {{ .Values.networkPolicy.dns.port }}
{{- end }}
