{{- if .Values.csi.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-kv-uat
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak-operator-istio.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.csi.clientId | quote }}
    keyvaultName: {{ .Values.csi.vaultName | quote }}
    cloudName: AzurePublicCloud
    tenantId: {{ .Values.csi.tenantId | quote }}
    objects: |
      array:
{{- range .Values.csi.objects.array }}
        - |
          objectName: {{ .objectName }}
          objectType: {{ .objectType }}
{{- end }}
  secretObjects:
    - secretName: {{ .Values.csi.secretName }}
      type: Opaque
      data:
        - key: {{ .Values.csi.keyMappings.dbUsername }}
          objectName: KC-DB-USERNAME
        - key: {{ .Values.csi.keyMappings.dbPassword }}
          objectName: KC-DB-PASSWORD
        - key: {{ .Values.csi.keyMappings.adminUsername }}
          objectName: KEYCLOAK-ADMIN
        - key: {{ .Values.csi.keyMappings.adminPassword }}
          objectName: KEYCLOAK-ADMIN-PASSWORD
{{- end }}
