# ---------- Builder ----------
FROM node:22-alpine AS builder

WORKDIR /app

# Install pnpm
RUN npm install -g pnpm@latest

# Copy only required files first
COPY package.json pnpm-lock.yaml ./

# Install dependencies
RUN pnpm install --frozen-lockfile

# Copy source
COPY . .

# Build VitePress
RUN pnpm build


# ---------- Runtime ----------
FROM nginx:alpine

# Clean default html
RUN rm -rf /usr/share/nginx/html/*

# Copy build output
COPY --from=builder /app/.vitepress/dist /usr/share/nginx/html

# Install libpng
RUN apk add --no-cache libpng

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]