apiVersion: v1
kind: Pod
metadata:
  name: cnpg-secret-sync
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "watershed-cnpg.labels" . | nindent 4 }}
spec:
  serviceAccountName: {{ .Values.serviceAccount.name }}
  containers:
    - name: sleep
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: {{ .Values.csiKeyVault.secretProviderClassName }}
  restartPolicy: Always
