apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: auragxp-redis-keyvault
  namespace: auragxp-db
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "5b2a0f44-83bf-4034-b0a9-ea002cadd130"
    keyvaultName: "kv-auraprod-esu"
    tenantId: "788f6d9e-1a66-4385-9aee-01da8900e00b"
    objects: |
      array:
        - |
          objectName: REDIS-PASSWORD
          objectType: secret
  secretObjects:
    - secretName: auragxp-redis-auth
      type: Opaque
      data:
        - objectName: REDIS-PASSWORD
          key: redis-password
