apiVersion: v2
name: watershed-redis
description: Redis for watershed platform
type: application
version: 0.1.0

dependencies:
  - name: redis
    version: 25.3.2
    repository: https://charts.bitnami.com/bitnami
