{{- if .Values.csiKeyVault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csiKeyVault.secretProviderClassName }}
  namespace: {{ .Values.networkPolicy.namespace | default .Values.namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.csiKeyVault.clientId | quote }}
    keyvaultName: {{ .Values.csiKeyVault.vaultName | quote }}
    tenantId: {{ .Values.csiKeyVault.tenantId | quote }}
    objects: |
      array:
{{- range .Values.csiKeyVault.objects.array }}
        - |
          objectName: {{ .objectName }}
          objectType: {{ .objectType }}
{{- end }}
  secretObjects:
    - secretName: {{ .Values.csiKeyVault.syncedK8sSecretName }}
      type: Opaque
      data:
{{- range .Values.csiKeyVault.secretObjects.data }}
        - objectName: {{ .objectName }}
          key: {{ .key }}
{{- end }}
{{- end }}
