
apiVersion: v1
kind: Pod
metadata:
  name: keyvault-secret-sync-test
  namespace: auragxp-keycloak-devint2
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: auragxp-serviceaccount-devint2
  restartPolicy: Never

  containers:
    - name: test
      image: busybox
      command:
        - sh
        - -c
        - "sleep 3600"

      volumeMounts:
        - name: secrets-store
          mountPath: /mnt/secrets
          readOnly: true

  volumes:
    - name: secrets-store
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: auragxp-keycloak-devint2-kv-devint2
