apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnpg-secret-sync
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cnpg-secret-sync
  template:
    metadata:
      labels:
        app: cnpg-secret-sync
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: sleep
        image: busybox
        command:
        - sh
        - -c
        - sleep infinity
        volumeMounts:
        - name: secrets-store-inline
          mountPath: /mnt/secrets-store
          readOnly: true

      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ .Values.csiKeyVault.secretProviderClassName }}
 