{{- if .Values.csiKeyVault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csiKeyVault.secretProviderClassName }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.csiKeyVault.clientId }}
    keyvaultName: {{ .Values.csiKeyVault.vaultName }}
    cloudName: AzurePublicCloud
    tenantId: {{ .Values.csiKeyVault.tenantId }}
    objects: |-
      array:
{{- range .Values.csiKeyVault.objects.array }}
        - |
          objectName: {{ .objectName }}
          objectType: {{ .objectType }}
{{- end }}
  secretObjects:
    # ===================== APP DB OWNER SECRET =====================
    - secretName: {{ .Values.csiKeyVault.syncedK8sSecretName }}
      type: Opaque
      data:
        - key: username
          objectName: POSTGRES-ADMIN-USER
        - key: password
          objectName: POSTGRES-ADMIN-PASSWORD
        - key: database
          objectName: POSTGRES-DB
        - key: CNPG_STORAGE_ACCOUNT
          objectName: CNPG-STORAGE-ACCOUNT
        - key: CNPG_STORAGE_ACCOUNT_KEY
          objectName: CNPG-STORAGE-ACCOUNT-KEY

{{- end }}
