{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.networkPolicy.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "watershed-support.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.appLabel }}
  policyTypes:
    {{- if .Values.networkPolicy.ingress.enabled }}
    - Ingress
    {{- end }}
    {{- if .Values.networkPolicy.egress.enabled }}
    - Egress
    {{- end }}
  {{- if .Values.networkPolicy.ingress.enabled }}
  ingress:
    {{- range .Values.networkPolicy.ingress.rules }}
    - from:
        {{- range .from }}
        {{- if .namespaceSelector }}
        - namespaceSelector:
            {{- toYaml .namespaceSelector | nindent 12 }}
          {{- if .podSelector }}
          podSelector:
            {{- toYaml .podSelector | nindent 12 }}
          {{- end }}
        {{- else if .podSelector }}
        - podSelector:
            {{- toYaml .podSelector | nindent 12 }}
        {{- else if .ipBlock }}
        - ipBlock:
            {{- toYaml .ipBlock | nindent 12 }}
        {{- end }}
        {{- end }}
      ports:
        {{- range .ports }}
        - protocol: {{ .protocol }}
          port: {{ .port }}
        {{- end }}
    {{- end }}
  {{- end }}
  {{- if .Values.networkPolicy.egress.enabled }}
  egress:
    {{- range .Values.networkPolicy.egress.rules }}
    - to:
        {{- range .to }}
        {{- if .namespaceSelector }}
        - namespaceSelector:
            {{- toYaml .namespaceSelector | nindent 12 }}
          {{- if .podSelector }}
          podSelector:
            {{- toYaml .podSelector | nindent 12 }}
          {{- end }}
        {{- else if .podSelector }}
        - podSelector:
            {{- toYaml .podSelector | nindent 12 }}
        {{- else if .ipBlock }}
        - ipBlock:
            {{- toYaml .ipBlock | nindent 12 }}
        {{- end }}
        {{- end }}
      ports:
        {{- range .ports }}
        - protocol: {{ .protocol }}
          port: {{ .port }}
        {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
