{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.serviceAccount.clientId }}
    azure.workload.identity/tenant-id: {{ .Values.serviceAccount.tenantId }}
{{- end }}