apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keycloak-operator
  namespace: auragxp-keycloak
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloak-operator
  namespace: auragxp-keycloak
subjects:
- kind: ServiceAccount
  name: keycloak-operator
  namespace: auragxp-keycloak
roleRef:
  kind: Role
  name: keycloak-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak-pod-sa
  namespace: auragxp-keycloak
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keycloak-pod-viewer
  namespace: auragxp-keycloak
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloak-pod-viewer-binding
  namespace: auragxp-keycloak
subjects:
- kind: ServiceAccount
  name: keycloak-pod-sa
roleRef:
  kind: Role
  name: keycloak-pod-viewer
  apiGroup: rbac.authorization.k8s.io
