apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-kv-prod
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak-operator-istio.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.csi.clientId }}
    keyvaultName: {{ .Values.csi.vaultName }}
    cloudName: AzurePublicCloud
    tenantId: {{ .Values.csi.tenantId }}
    objects: |
      array:
        - |
          objectName: KC-DB-USERNAME
          objectType: secret
        - |
          objectName: KC-DB-PASSWORD
          objectType: secret
        - |
          objectName: KEYCLOAK-ADMIN
          objectType: secret
        - |
          objectName: KEYCLOAK-ADMIN-PASSWORD
          objectType: secret
  secretObjects:
    - secretName: {{ .Values.csi.secretName }}
      type: Opaque
      data:
        - key: {{ .Values.csi.keyMappings.dbUsername }}
          objectName: KC-DB-USERNAME
        - key: {{ .Values.csi.keyMappings.dbPassword }}
          objectName: KC-DB-PASSWORD
        - key: {{ .Values.csi.keyMappings.adminUsername }}
          objectName: KEYCLOAK-ADMIN
        - key: {{ .Values.csi.keyMappings.adminPassword }}
          objectName: KEYCLOAK-ADMIN-PASSWORD
