apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: auragxp-db-devint2-cluster
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ .Values.istio.dbClusterHost }}
  trafficPolicy:
    tls:
      mode: DISABLE
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 10
        maxRequestsPerConnection: 10
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: auragxp-db-devint2-cluster-ro
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ .Values.istio.dbClusterRoHost }}
  trafficPolicy:
    tls:
      mode: DISABLE
