apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: azure-scorm-dr
  namespace: {{ .Values.namespace }}
spec:
  host: {{ .Values.externalServices.scorm.host }}
  trafficPolicy:
    tls:
      mode: SIMPLE
