{{- if .Values.csiKeyVault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csiKeyVault.secretProviderClassName }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.csiKeyVault.clientId }}
    keyvaultName: {{ .Values.csiKeyVault.vaultName }}
    cloudName: AzurePublicCloud
    tenantId: {{ .Values.csiKeyVault.tenantId }}
    objects: |-
      array:
{{- range .Values.csiKeyVault.objects.array }}
        - |
          objectName: {{ .objectName }}
          objectType: {{ .objectType }}
{{- end }}

  secretObjects:
    - secretName: {{ .Values.csiKeyVault.syncedK8sSecretName }}
      type: Opaque
      data:
        - key: PORT
          objectName: PORT
        - key: SP_ENV
          objectName: SP-ENV
        - key: DB_HOST
          objectName: DB-HOST
        - key: DB_PORT
          objectName: DB-PORT
        - key: DB_USER
          objectName: DB-USER
        - key: DB_PASSWORD
          objectName: DB-PASSWORD
        - key: DB_NAME
          objectName: DB-NAME
        - key: AZURE_TENANT_ID
          objectName: AZURE-TENANT-ID
        - key: AZURE_CLIENT_ID
          objectName: AZURE-CLIENT-ID
        - key: AZURE_CLIENT_SECRET
          objectName: AZURE-CLIENT-SECRET
        - key: AZURE_STORAGE_CONTAINER_NAME
          objectName: AZURE-STORAGE-CONTAINER-NAME
        - key: AZURE_STORAGE_ACCOUNT_NAME
          objectName: AZURE-STORAGE-ACCOUNT-NAME
        - key: AZURE_STORAGE_CONNECTION_STRING
          objectName: AZURE-STORAGE-CONNECTION-STRING
        - key: SHAREPOINT_SITE_ID
          objectName: SHAREPOINT-SITE-ID
        - key: SHAREPOINT_DRIVE_ID
          objectName: SHAREPOINT-DRIVE-ID
        - key: KEYCLOAK_ISSUER
          objectName: BACKEND-KEYCLOAK-ISSUER
        - key: KEYCLOAK_CLIENT_ID
          objectName: BACKEND-KEYCLOAK-CLIENT-ID
        - key: KEYCLOAK_CLIENT_SECRET
          objectName: BACKEND-KEYCLOAK-CLIENT-SECRET
        - key: KEYCLOAK_REDIRECT_URI
          objectName: BACKEND-KEYCLOAK-REDIRECT-URI
        - key: KEYCLOAK_ADMIN_CLIENT_ID
          objectName: BACKEND-KEYCLOAK-ADMIN-CLIENT-ID
        - key: KEYCLOAK_ADMIN_CLIENT_SECRET
          objectName: BACKEND-KEYCLOAK-ADMIN-CLIENT-SECRET
        - key: KC_BASE_URL
          objectName: BACKEND-KC-BASE-URL
        - key: KEYCLOAK_REALM
          objectName: BACKEND-KEYCLOAK-REALM
        - key: KEYCLOAK_AUDIENCE
          objectName: BACKEND-KEYCLOAK-AUDIENCE
        - key: KEYCLOAK_JWKS
          objectName: BACKEND-KEYCLOAK-JWKS
        - key: LICENSE_SERVER_URL
          objectName: LICENSE-SERVER-URL
        - key: LICENSE_CLIENT_ID
          objectName: LICENSE-CLIENT-ID
        - key: LICENSE_CLIENT_SECRET
          objectName: LICENSE-CLIENT-SECRET
        - key: KEYCLOAK_ADMIN
          objectName: KEYCLOAK-ADMIN
        - key: KEYCLOAK_ADMIN_PASSWORD
          objectName: KEYCLOAK-ADMIN-PASSWORD
        - key: KC_DB_USERNAME
          objectName: KC-DB-USERNAME
        - key: KC_DB_PASSWORD
          objectName: KC-DB-PASSWORD
        - key: COMMUNICATION_SERVICES_CONNECTION_STRING
          objectName: COMMUNICATION-SERVICES-CONNECTION-STRING
        - key: ACS_SENDER_ADDRESS
          objectName: ACS-SENDER-ADDRESS
        - key: DEV_URL
          objectName: DEV-URL
        - key: FUNCTION_APP_URL
          objectName: FUNCTION-APP-URL
        - key: REDIS_PASSWORD
          objectName: REDIS-PASSWORD
        - key: POSTGRES_ADMIN_USER
          objectName: POSTGRES-ADMIN-USER
        - key: ORG_PROVISION_FUNCTION_URL
          objectName: ORG-PROVISION-FUNCTION-URL
        - key: ORG_SCHEMA_VERSION
          objectName: ORG-SCHEMA-VERSION
        - key: TEMP_PASSWORD
          objectName: TEMP-PASSWORD
        - key: WORKFLOW_EMAILS
          objectName: WORKFLOW-EMAILS
{{- end }}
