{{- if .Values.csiKeyVault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: auragxp-frontend-kv-prod
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.csiKeyVault.clientId }}
    keyvaultName: {{ .Values.csiKeyVault.vaultName }}
    cloudName: AzurePublicCloud
    tenantId: {{ .Values.csiKeyVault.tenantId }}
    objects: |-
      array:
        - |
          objectName: NEXTAUTH-URL
          objectType: secret
        - |
          objectName: NEXTAUTH-SECRET
          objectType: secret
        - |
          objectName: KEYCLOAK-ISSUER
          objectType: secret
        - |
          objectName: KEYCLOAK-CLIENT-ID
          objectType: secret
        - |
          objectName: KEYCLOAK-CLIENT-SECRET
          objectType: secret

  secretObjects:
    - secretName: auragxp-frontend-secrets-prod
      type: Opaque
      data:
        - key: NEXTAUTH_URL
          objectName: NEXTAUTH-URL
        - key: NEXTAUTH_SECRET
          objectName: NEXTAUTH-SECRET
        - key: KEYCLOAK_ISSUER
          objectName: KEYCLOAK-ISSUER
        - key: KEYCLOAK_CLIENT_ID
          objectName: KEYCLOAK-CLIENT-ID
        - key: KEYCLOAK_CLIENT_SECRET
          objectName: KEYCLOAK-CLIENT-SECRET
{{- end }}

