{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: auragxp-support-dr
  namespace: {{ .Values.namespace }}
spec:
  host: auragxp-support
  trafficPolicy:
    tls:
      mode: DISABLE
{{- end }}

