apiVersion: v2
name: auragxp-redis-devint2
description: Redis for Auragxp DevInt2 platform
type: application
version: 0.1.0

dependencies:
  - name: redis
    version: 25.3.2
    repository: https://charts.bitnami.com/bitnami
